title: GeorgSMZ
email: g.binus@gmx.net
description: I also have a Blog-Website, where I release experience in coding and my generell life.
twitter_username: GeorgSMZ
github_username:  jekyll

# Build settings
theme: minima

